---
# handlers file for createVM_builder
- name: isRunningVM
  gcp_compute_instance:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    name: "{{ instance_name }}"
    machine_type: "{{ machine_type }}"
    zone: "{{ region }}-{{ zone }}"
    status: RUNNING